{% set name = "gemmi" %}
{% set version = "0.5.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - pybind11
  run:
    - python

test:
  imports:
    - gemmi

about:
  home: "https://project-gemmi.github.io/"
  license: "Mozilla Public 2.0 (MPL 2.0)"
  license_family: MOZILLA
  summary: "library for structural biology"
